version: "3.9"

services:
  churn-api:
    build: .
    image: churn-api:latest
    container_name: churn-api-compose
    ports:
      - "8000:8000"
    environment:
      LOG_LEVEL: "info"
    # Optionnel : monter les dossiers pour la persistance
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - ./registry:/app/registry